import type { Metadata } from "next";
import "./globals.css";
import { Istok_Web } from "next/font/google";

const istokWeb = Istok_Web({
  variable: "--font-istok-web",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${istokWeb.variable} antialiased`}>{children}</body>
    </html>
  );
}
